name: Bug report
description: Report a reproducible problem in the app
title: "[Bug] "
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the bug in 1-3 sentences.
      placeholder: A clear and concise summary of the problem.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List exact steps so someone else can reproduce it.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Enter/select ...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What happened instead?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / recording
      description: Attach images or a short recording if possible.

  - type: input
    id: app_version
    attributes:
      label: App version / commit
      placeholder: e.g. 3e8ff9f

  - type: input
    id: browser
    attributes:
      label: Browser and version
      placeholder: e.g. Chrome 133
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS and version
      placeholder: e.g. macOS 15.3
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      placeholder: e.g. MacBook Air M2 / iPhone 15

  - type: input
    id: issue_url
    attributes:
      label: URL where issue occurred
      placeholder: https://...

  - type: textarea
    id: logs
    attributes:
      label: Console / network errors
      render: text
      placeholder: Paste relevant console or network errors.

  - type: input
    id: coords
    attributes:
      label: Coordinates (lat/lon)
      placeholder: e.g. 51.5074, -0.1278

  - type: input
    id: city
    attributes:
      label: City searched
      placeholder: e.g. London

  - type: input
    id: layer
    attributes:
      label: Map layer selected
      placeholder: e.g. clouds_new

  - type: input
    id: issue_time
    attributes:
      label: Time of issue (local timezone)
      placeholder: e.g. 2026-02-22 10:45 PST

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      placeholder: Any extra details that might help debugging.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues before creating this report.
          required: true
        - label: I can reproduce this issue consistently.
          required: false
